GET http://localhost:1234/pokemon/ditto

### Bad request test
GET http://localhost:1234/pokemon/badrequest

### Para crear un Pokemon
POST http://localhost:1234/pokemon
Content-Type: application/json

{
    "name": "ditto",
    "type": "normal",
    "moves": [
        "transform"
    ]
}